### ISSUE TITLE
Peer code review

### ISSUE THREAD

**Issue by MrSampy** [ImLewel/lab4_SDMT#2]
1.You should remove junk usings like here https://github.com/ImLewel/lab4_SDMT/blob/master/ToDoListApp/ToDoList.cs#L1-L6
```c#
﻿using System; // <- this one
using System.Collections.Generic;  // <- this one
using System.Linq;  // <- this one
using System.Text;  // <- this one
using System.Threading.Tasks; // <- this one
using Newtonsoft.Json;
```
2.The savePath variable is hardcoded as "../../../data.txt". I think it`s better to avoid hardcoded paths and instead provide a more flexible approach, such as allowing the path to be passed as a parameter or configurable through a settings file.
https://github.com/ImLewel/lab4_SDMT/blob/master/ToDoListApp/ToDoList.cs#L10
3.The code lacks proper error handling. 
4.Class names should use PascalCase, so consider renaming TDTask to TdTask to follow the convention.
https://github.com/ImLewel/lab4_SDMT/blob/master/ToDoListApp/Task.cs#L10
```c#
public class TdTask 
{
   ...
}
```
4.Instead of using public fields, I think it`s  better to use properties with proper encapsulation (getters and setters) for better control and maintainability.  And maybe for better readability of code, you should add modifiers to fileds Like this:
```c#
    public string Caption { get; set; }
    public string Description { get; set; }
    public string DeadLine { get; set; }
    private readonly bool Done = false;
    private readonly CultureInfo Culture = new CultureInfo("en-EN");
    private readonly string Pattern = "yyyy dd MMMM HH:mm";
```
5.If you want to represent the absence of a deadline, it might be better to use a nullable type (DateTime?) for the deadLine property instead of using a string value like "No deadline." 
```c#
    
    public DateTime? DeadLine { get; set; }
    
      [JsonConstructor]
      public TdTask(string caption, string description, DateTime deadline)
      {
          Caption = caption;
          Description = description;
          Deadline = deadline;
      }

      public TdTask(string caption, string description)
      {
          Caption = caption;
          Description = description;
          Deadline = null;
      }
```

**Comment by ImLewel** [comment]
Thanks, waiting for further reviews!
